name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./assignment_5  # Changed to assignment_5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Force CPU-only PyTorch installation
        pip install torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install numpy>=1.19.2 tqdm>=4.65.0
        
    - name: Train model
      run: |
        python src/train.py
        cp model_mnist_*.pth model_mnist_latest.pth
        
    - name: Run tests
      run: |
        python -m unittest discover tests
        
    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: assignment_5/model_mnist_*.pth  # Changed to assignment_5