name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./assignment_5  # Changed to assignment_5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install -r requirements.txt
        
    - name: Train model
      run: |
        python src/train.py
        cp model_mnist_*.pth model_mnist_latest.pth
        
    - name: Run tests
      run: |
        python -m unittest discover tests
        
    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: assignment_5/model_mnist_*.pth
        compression: true
        if-no-files-found: warn